/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { TENSORSWAP_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getPoolConfigDecoder,
  getPoolConfigEncoder,
  type PoolConfig,
  type PoolConfigArgs,
} from "../types";

export const ATTACH_POOL_TO_MARGIN_DISCRIMINATOR = new Uint8Array([
  187, 105, 211, 137, 224, 59, 29, 227,
]);

export function getAttachPoolToMarginDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ATTACH_POOL_TO_MARGIN_DISCRIMINATOR,
  );
}

export type AttachPoolToMarginInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountTswap extends string | IAccountMeta<string> = string,
  TAccountMarginAccount extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountWhitelist extends string | IAccountMeta<string> = string,
  TAccountSolEscrow extends string | IAccountMeta<string> = string,
  TAccountOwner extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountTswap extends string
        ? ReadonlyAccount<TAccountTswap>
        : TAccountTswap,
      TAccountMarginAccount extends string
        ? WritableAccount<TAccountMarginAccount>
        : TAccountMarginAccount,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountWhitelist extends string
        ? ReadonlyAccount<TAccountWhitelist>
        : TAccountWhitelist,
      TAccountSolEscrow extends string
        ? WritableAccount<TAccountSolEscrow>
        : TAccountSolEscrow,
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            IAccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AttachPoolToMarginInstructionData = {
  discriminator: ReadonlyUint8Array;
  config: PoolConfig;
};

export type AttachPoolToMarginInstructionDataArgs = { config: PoolConfigArgs };

export function getAttachPoolToMarginInstructionDataEncoder(): Encoder<AttachPoolToMarginInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["config", getPoolConfigEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: ATTACH_POOL_TO_MARGIN_DISCRIMINATOR,
    }),
  );
}

export function getAttachPoolToMarginInstructionDataDecoder(): Decoder<AttachPoolToMarginInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["config", getPoolConfigDecoder()],
  ]);
}

export function getAttachPoolToMarginInstructionDataCodec(): Codec<
  AttachPoolToMarginInstructionDataArgs,
  AttachPoolToMarginInstructionData
> {
  return combineCodec(
    getAttachPoolToMarginInstructionDataEncoder(),
    getAttachPoolToMarginInstructionDataDecoder(),
  );
}

export type AttachPoolToMarginInput<
  TAccountTswap extends string = string,
  TAccountMarginAccount extends string = string,
  TAccountPool extends string = string,
  TAccountWhitelist extends string = string,
  TAccountSolEscrow extends string = string,
  TAccountOwner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  tswap: Address<TAccountTswap>;
  marginAccount: Address<TAccountMarginAccount>;
  pool: Address<TAccountPool>;
  /** Needed for pool seeds derivation / will be stored inside pool */
  whitelist: Address<TAccountWhitelist>;
  solEscrow: Address<TAccountSolEscrow>;
  owner: TransactionSigner<TAccountOwner>;
  systemProgram?: Address<TAccountSystemProgram>;
  config: AttachPoolToMarginInstructionDataArgs["config"];
};

export function getAttachPoolToMarginInstruction<
  TAccountTswap extends string,
  TAccountMarginAccount extends string,
  TAccountPool extends string,
  TAccountWhitelist extends string,
  TAccountSolEscrow extends string,
  TAccountOwner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TENSORSWAP_PROGRAM_ADDRESS,
>(
  input: AttachPoolToMarginInput<
    TAccountTswap,
    TAccountMarginAccount,
    TAccountPool,
    TAccountWhitelist,
    TAccountSolEscrow,
    TAccountOwner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AttachPoolToMarginInstruction<
  TProgramAddress,
  TAccountTswap,
  TAccountMarginAccount,
  TAccountPool,
  TAccountWhitelist,
  TAccountSolEscrow,
  TAccountOwner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? TENSORSWAP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    tswap: { value: input.tswap ?? null, isWritable: false },
    marginAccount: { value: input.marginAccount ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
    whitelist: { value: input.whitelist ?? null, isWritable: false },
    solEscrow: { value: input.solEscrow ?? null, isWritable: true },
    owner: { value: input.owner ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.tswap),
      getAccountMeta(accounts.marginAccount),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.whitelist),
      getAccountMeta(accounts.solEscrow),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getAttachPoolToMarginInstructionDataEncoder().encode(
      args as AttachPoolToMarginInstructionDataArgs,
    ),
  } as AttachPoolToMarginInstruction<
    TProgramAddress,
    TAccountTswap,
    TAccountMarginAccount,
    TAccountPool,
    TAccountWhitelist,
    TAccountSolEscrow,
    TAccountOwner,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedAttachPoolToMarginInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    tswap: TAccountMetas[0];
    marginAccount: TAccountMetas[1];
    pool: TAccountMetas[2];
    /** Needed for pool seeds derivation / will be stored inside pool */
    whitelist: TAccountMetas[3];
    solEscrow: TAccountMetas[4];
    owner: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: AttachPoolToMarginInstructionData;
};

export function parseAttachPoolToMarginInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedAttachPoolToMarginInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      tswap: getNextAccount(),
      marginAccount: getNextAccount(),
      pool: getNextAccount(),
      whitelist: getNextAccount(),
      solEscrow: getNextAccount(),
      owner: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAttachPoolToMarginInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
