/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { TENSORSWAP_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getPoolConfigDecoder,
  getPoolConfigEncoder,
  type PoolConfig,
  type PoolConfigArgs,
} from "../types";

export const EDIT_POOL_IN_PLACE_DISCRIMINATOR = new Uint8Array([
  125, 191, 119, 113, 6, 14, 164, 23,
]);

export function getEditPoolInPlaceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EDIT_POOL_IN_PLACE_DISCRIMINATOR,
  );
}

export type EditPoolInPlaceInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountTswap extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountWhitelist extends string | IAccountMeta<string> = string,
  TAccountOwner extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountTswap extends string
        ? ReadonlyAccount<TAccountTswap>
        : TAccountTswap,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountWhitelist extends string
        ? ReadonlyAccount<TAccountWhitelist>
        : TAccountWhitelist,
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            IAccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type EditPoolInPlaceInstructionData = {
  discriminator: ReadonlyUint8Array;
  config: PoolConfig;
  isCosigned: Option<boolean>;
  maxTakerSellCount: Option<number>;
  mmCompoundFees: Option<boolean>;
};

export type EditPoolInPlaceInstructionDataArgs = {
  config: PoolConfigArgs;
  isCosigned: OptionOrNullable<boolean>;
  maxTakerSellCount: OptionOrNullable<number>;
  mmCompoundFees: OptionOrNullable<boolean>;
};

export function getEditPoolInPlaceInstructionDataEncoder(): Encoder<EditPoolInPlaceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["config", getPoolConfigEncoder()],
      ["isCosigned", getOptionEncoder(getBooleanEncoder())],
      ["maxTakerSellCount", getOptionEncoder(getU32Encoder())],
      ["mmCompoundFees", getOptionEncoder(getBooleanEncoder())],
    ]),
    (value) => ({ ...value, discriminator: EDIT_POOL_IN_PLACE_DISCRIMINATOR }),
  );
}

export function getEditPoolInPlaceInstructionDataDecoder(): Decoder<EditPoolInPlaceInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["config", getPoolConfigDecoder()],
    ["isCosigned", getOptionDecoder(getBooleanDecoder())],
    ["maxTakerSellCount", getOptionDecoder(getU32Decoder())],
    ["mmCompoundFees", getOptionDecoder(getBooleanDecoder())],
  ]);
}

export function getEditPoolInPlaceInstructionDataCodec(): Codec<
  EditPoolInPlaceInstructionDataArgs,
  EditPoolInPlaceInstructionData
> {
  return combineCodec(
    getEditPoolInPlaceInstructionDataEncoder(),
    getEditPoolInPlaceInstructionDataDecoder(),
  );
}

export type EditPoolInPlaceInput<
  TAccountTswap extends string = string,
  TAccountPool extends string = string,
  TAccountWhitelist extends string = string,
  TAccountOwner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  tswap: Address<TAccountTswap>;
  pool: Address<TAccountPool>;
  /** Needed for pool seeds derivation / will be stored inside pool */
  whitelist: Address<TAccountWhitelist>;
  owner: TransactionSigner<TAccountOwner>;
  systemProgram?: Address<TAccountSystemProgram>;
  config: EditPoolInPlaceInstructionDataArgs["config"];
  isCosigned: EditPoolInPlaceInstructionDataArgs["isCosigned"];
  maxTakerSellCount: EditPoolInPlaceInstructionDataArgs["maxTakerSellCount"];
  mmCompoundFees: EditPoolInPlaceInstructionDataArgs["mmCompoundFees"];
};

export function getEditPoolInPlaceInstruction<
  TAccountTswap extends string,
  TAccountPool extends string,
  TAccountWhitelist extends string,
  TAccountOwner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TENSORSWAP_PROGRAM_ADDRESS,
>(
  input: EditPoolInPlaceInput<
    TAccountTswap,
    TAccountPool,
    TAccountWhitelist,
    TAccountOwner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): EditPoolInPlaceInstruction<
  TProgramAddress,
  TAccountTswap,
  TAccountPool,
  TAccountWhitelist,
  TAccountOwner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? TENSORSWAP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    tswap: { value: input.tswap ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    whitelist: { value: input.whitelist ?? null, isWritable: false },
    owner: { value: input.owner ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.tswap),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.whitelist),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getEditPoolInPlaceInstructionDataEncoder().encode(
      args as EditPoolInPlaceInstructionDataArgs,
    ),
  } as EditPoolInPlaceInstruction<
    TProgramAddress,
    TAccountTswap,
    TAccountPool,
    TAccountWhitelist,
    TAccountOwner,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedEditPoolInPlaceInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    tswap: TAccountMetas[0];
    pool: TAccountMetas[1];
    /** Needed for pool seeds derivation / will be stored inside pool */
    whitelist: TAccountMetas[2];
    owner: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: EditPoolInPlaceInstructionData;
};

export function parseEditPoolInPlaceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedEditPoolInPlaceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      tswap: getNextAccount(),
      pool: getNextAccount(),
      whitelist: getNextAccount(),
      owner: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getEditPoolInPlaceInstructionDataDecoder().decode(instruction.data),
  };
}
