/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { TENSORSWAP_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const EDIT_SINGLE_LISTING_DISCRIMINATOR = new Uint8Array([
  88, 38, 236, 212, 31, 185, 18, 166,
]);

export function getEditSingleListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EDIT_SINGLE_LISTING_DISCRIMINATOR,
  );
}

export type EditSingleListingInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountSingleListing extends string | IAccountMeta<string> = string,
  TAccountNftMint extends string | IAccountMeta<string> = string,
  TAccountOwner extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountSingleListing extends string
        ? WritableAccount<TAccountSingleListing>
        : TAccountSingleListing,
      TAccountNftMint extends string
        ? ReadonlyAccount<TAccountNftMint>
        : TAccountNftMint,
      TAccountOwner extends string
        ? ReadonlySignerAccount<TAccountOwner> &
            IAccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type EditSingleListingInstructionData = {
  discriminator: ReadonlyUint8Array;
  price: bigint;
};

export type EditSingleListingInstructionDataArgs = { price: number | bigint };

export function getEditSingleListingInstructionDataEncoder(): Encoder<EditSingleListingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["price", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: EDIT_SINGLE_LISTING_DISCRIMINATOR }),
  );
}

export function getEditSingleListingInstructionDataDecoder(): Decoder<EditSingleListingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["price", getU64Decoder()],
  ]);
}

export function getEditSingleListingInstructionDataCodec(): Codec<
  EditSingleListingInstructionDataArgs,
  EditSingleListingInstructionData
> {
  return combineCodec(
    getEditSingleListingInstructionDataEncoder(),
    getEditSingleListingInstructionDataDecoder(),
  );
}

export type EditSingleListingInput<
  TAccountSingleListing extends string = string,
  TAccountNftMint extends string = string,
  TAccountOwner extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  singleListing: Address<TAccountSingleListing>;
  nftMint: Address<TAccountNftMint>;
  owner: TransactionSigner<TAccountOwner>;
  systemProgram?: Address<TAccountSystemProgram>;
  price: EditSingleListingInstructionDataArgs["price"];
};

export function getEditSingleListingInstruction<
  TAccountSingleListing extends string,
  TAccountNftMint extends string,
  TAccountOwner extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TENSORSWAP_PROGRAM_ADDRESS,
>(
  input: EditSingleListingInput<
    TAccountSingleListing,
    TAccountNftMint,
    TAccountOwner,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): EditSingleListingInstruction<
  TProgramAddress,
  TAccountSingleListing,
  TAccountNftMint,
  TAccountOwner,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? TENSORSWAP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    singleListing: { value: input.singleListing ?? null, isWritable: true },
    nftMint: { value: input.nftMint ?? null, isWritable: false },
    owner: { value: input.owner ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.singleListing),
      getAccountMeta(accounts.nftMint),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getEditSingleListingInstructionDataEncoder().encode(
      args as EditSingleListingInstructionDataArgs,
    ),
  } as EditSingleListingInstruction<
    TProgramAddress,
    TAccountSingleListing,
    TAccountNftMint,
    TAccountOwner,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedEditSingleListingInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    singleListing: TAccountMetas[0];
    nftMint: TAccountMetas[1];
    owner: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: EditSingleListingInstructionData;
};

export function parseEditSingleListingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedEditSingleListingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      singleListing: getNextAccount(),
      nftMint: getNextAccount(),
      owner: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getEditSingleListingInstructionDataDecoder().decode(instruction.data),
  };
}
