/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { TENSORSWAP_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getPoolConfigDecoder,
  getPoolConfigEncoder,
  type PoolConfig,
  type PoolConfigArgs,
} from "../types";

export const SET_POOL_FREEZE_DISCRIMINATOR = new Uint8Array([
  110, 201, 190, 64, 166, 186, 105, 131,
]);

export function getSetPoolFreezeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_POOL_FREEZE_DISCRIMINATOR,
  );
}

export type SetPoolFreezeInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SetPoolFreezeInstructionData = {
  discriminator: ReadonlyUint8Array;
  config: PoolConfig;
  freeze: boolean;
};

export type SetPoolFreezeInstructionDataArgs = {
  config: PoolConfigArgs;
  freeze: boolean;
};

export function getSetPoolFreezeInstructionDataEncoder(): Encoder<SetPoolFreezeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["config", getPoolConfigEncoder()],
      ["freeze", getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_POOL_FREEZE_DISCRIMINATOR }),
  );
}

export function getSetPoolFreezeInstructionDataDecoder(): Decoder<SetPoolFreezeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["config", getPoolConfigDecoder()],
    ["freeze", getBooleanDecoder()],
  ]);
}

export function getSetPoolFreezeInstructionDataCodec(): Codec<
  SetPoolFreezeInstructionDataArgs,
  SetPoolFreezeInstructionData
> {
  return combineCodec(
    getSetPoolFreezeInstructionDataEncoder(),
    getSetPoolFreezeInstructionDataDecoder(),
  );
}

export type SetPoolFreezeInput<TAccountSystemProgram extends string = string> =
  {
    systemProgram?: Address<TAccountSystemProgram>;
    config: SetPoolFreezeInstructionDataArgs["config"];
    freeze: SetPoolFreezeInstructionDataArgs["freeze"];
  };

export function getSetPoolFreezeInstruction<
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TENSORSWAP_PROGRAM_ADDRESS,
>(
  input: SetPoolFreezeInput<TAccountSystemProgram>,
  config?: { programAddress?: TProgramAddress },
): SetPoolFreezeInstruction<TProgramAddress, TAccountSystemProgram> {
  // Program address.
  const programAddress = config?.programAddress ?? TENSORSWAP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [getAccountMeta(accounts.systemProgram)],
    programAddress,
    data: getSetPoolFreezeInstructionDataEncoder().encode(
      args as SetPoolFreezeInstructionDataArgs,
    ),
  } as SetPoolFreezeInstruction<TProgramAddress, TAccountSystemProgram>;

  return instruction;
}

export type ParsedSetPoolFreezeInstruction<
  TProgram extends string = typeof TENSORSWAP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    systemProgram: TAccountMetas[0];
  };
  data: SetPoolFreezeInstructionData;
};

export function parseSetPoolFreezeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedSetPoolFreezeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      systemProgram: getNextAccount(),
    },
    data: getSetPoolFreezeInstructionDataDecoder().decode(instruction.data),
  };
}
