/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { TENSOR_BID_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const BID_DISCRIMINATOR = new Uint8Array([
  199, 56, 85, 38, 146, 243, 37, 158,
]);

export function getBidDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(BID_DISCRIMINATOR);
}

export type BidInstruction<
  TProgram extends string = typeof TENSOR_BID_PROGRAM_ADDRESS,
  TAccountNftMint extends string | IAccountMeta<string> = string,
  TAccountBidState extends string | IAccountMeta<string> = string,
  TAccountBidder extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = "11111111111111111111111111111111",
  TAccountRent extends
    | string
    | IAccountMeta<string> = "SysvarRent111111111111111111111111111111111",
  TAccountTswap extends string | IAccountMeta<string> = string,
  TAccountMarginAccount extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNftMint extends string
        ? ReadonlyAccount<TAccountNftMint>
        : TAccountNftMint,
      TAccountBidState extends string
        ? WritableAccount<TAccountBidState>
        : TAccountBidState,
      TAccountBidder extends string
        ? WritableSignerAccount<TAccountBidder> &
            IAccountSignerMeta<TAccountBidder>
        : TAccountBidder,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      TAccountTswap extends string
        ? ReadonlyAccount<TAccountTswap>
        : TAccountTswap,
      TAccountMarginAccount extends string
        ? WritableAccount<TAccountMarginAccount>
        : TAccountMarginAccount,
      ...TRemainingAccounts,
    ]
  >;

export type BidInstructionData = {
  discriminator: ReadonlyUint8Array;
  lamports: bigint;
  expireInSec: Option<bigint>;
};

export type BidInstructionDataArgs = {
  lamports: number | bigint;
  expireInSec: OptionOrNullable<number | bigint>;
};

export function getBidInstructionDataEncoder(): Encoder<BidInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["lamports", getU64Encoder()],
      ["expireInSec", getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({ ...value, discriminator: BID_DISCRIMINATOR }),
  );
}

export function getBidInstructionDataDecoder(): Decoder<BidInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["lamports", getU64Decoder()],
    ["expireInSec", getOptionDecoder(getU64Decoder())],
  ]);
}

export function getBidInstructionDataCodec(): Codec<
  BidInstructionDataArgs,
  BidInstructionData
> {
  return combineCodec(
    getBidInstructionDataEncoder(),
    getBidInstructionDataDecoder(),
  );
}

export type BidInput<
  TAccountNftMint extends string = string,
  TAccountBidState extends string = string,
  TAccountBidder extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
  TAccountTswap extends string = string,
  TAccountMarginAccount extends string = string,
> = {
  nftMint: Address<TAccountNftMint>;
  bidState: Address<TAccountBidState>;
  bidder: TransactionSigner<TAccountBidder>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  tswap: Address<TAccountTswap>;
  marginAccount: Address<TAccountMarginAccount>;
  lamports: BidInstructionDataArgs["lamports"];
  expireInSec: BidInstructionDataArgs["expireInSec"];
};

export function getBidInstruction<
  TAccountNftMint extends string,
  TAccountBidState extends string,
  TAccountBidder extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TAccountTswap extends string,
  TAccountMarginAccount extends string,
  TProgramAddress extends Address = typeof TENSOR_BID_PROGRAM_ADDRESS,
>(
  input: BidInput<
    TAccountNftMint,
    TAccountBidState,
    TAccountBidder,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTswap,
    TAccountMarginAccount
  >,
  config?: { programAddress?: TProgramAddress },
): BidInstruction<
  TProgramAddress,
  TAccountNftMint,
  TAccountBidState,
  TAccountBidder,
  TAccountSystemProgram,
  TAccountRent,
  TAccountTswap,
  TAccountMarginAccount
> {
  // Program address.
  const programAddress = config?.programAddress ?? TENSOR_BID_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    nftMint: { value: input.nftMint ?? null, isWritable: false },
    bidState: { value: input.bidState ?? null, isWritable: true },
    bidder: { value: input.bidder ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
    tswap: { value: input.tswap ?? null, isWritable: false },
    marginAccount: { value: input.marginAccount ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.nftMint),
      getAccountMeta(accounts.bidState),
      getAccountMeta(accounts.bidder),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.tswap),
      getAccountMeta(accounts.marginAccount),
    ],
    programAddress,
    data: getBidInstructionDataEncoder().encode(args as BidInstructionDataArgs),
  } as BidInstruction<
    TProgramAddress,
    TAccountNftMint,
    TAccountBidState,
    TAccountBidder,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTswap,
    TAccountMarginAccount
  >;

  return instruction;
}

export type ParsedBidInstruction<
  TProgram extends string = typeof TENSOR_BID_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    nftMint: TAccountMetas[0];
    bidState: TAccountMetas[1];
    bidder: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
    rent: TAccountMetas[4];
    tswap: TAccountMetas[5];
    marginAccount: TAccountMetas[6];
  };
  data: BidInstructionData;
};

export function parseBidInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedBidInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      nftMint: getNextAccount(),
      bidState: getNextAccount(),
      bidder: getNextAccount(),
      systemProgram: getNextAccount(),
      rent: getNextAccount(),
      tswap: getNextAccount(),
      marginAccount: getNextAccount(),
    },
    data: getBidInstructionDataDecoder().decode(instruction.data),
  };
}
