/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { TENSOR_BID_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CANCEL_BID_DISCRIMINATOR = new Uint8Array([
  40, 243, 190, 217, 208, 253, 86, 206,
]);

export function getCancelBidDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CANCEL_BID_DISCRIMINATOR);
}

export type CancelBidInstruction<
  TProgram extends string = typeof TENSOR_BID_PROGRAM_ADDRESS,
  TAccountNftMint extends string | IAccountMeta<string> = string,
  TAccountBidState extends string | IAccountMeta<string> = string,
  TAccountBidder extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = "11111111111111111111111111111111",
  TAccountRent extends
    | string
    | IAccountMeta<string> = "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNftMint extends string
        ? ReadonlyAccount<TAccountNftMint>
        : TAccountNftMint,
      TAccountBidState extends string
        ? WritableAccount<TAccountBidState>
        : TAccountBidState,
      TAccountBidder extends string
        ? WritableSignerAccount<TAccountBidder> &
            IAccountSignerMeta<TAccountBidder>
        : TAccountBidder,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type CancelBidInstructionData = { discriminator: ReadonlyUint8Array };

export type CancelBidInstructionDataArgs = object;

export function getCancelBidInstructionDataEncoder(): Encoder<CancelBidInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CANCEL_BID_DISCRIMINATOR }),
  );
}

export function getCancelBidInstructionDataDecoder(): Decoder<CancelBidInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCancelBidInstructionDataCodec(): Codec<
  CancelBidInstructionDataArgs,
  CancelBidInstructionData
> {
  return combineCodec(
    getCancelBidInstructionDataEncoder(),
    getCancelBidInstructionDataDecoder(),
  );
}

export type CancelBidInput<
  TAccountNftMint extends string = string,
  TAccountBidState extends string = string,
  TAccountBidder extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  nftMint: Address<TAccountNftMint>;
  bidState: Address<TAccountBidState>;
  bidder: TransactionSigner<TAccountBidder>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
};

export function getCancelBidInstruction<
  TAccountNftMint extends string,
  TAccountBidState extends string,
  TAccountBidder extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof TENSOR_BID_PROGRAM_ADDRESS,
>(
  input: CancelBidInput<
    TAccountNftMint,
    TAccountBidState,
    TAccountBidder,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): CancelBidInstruction<
  TProgramAddress,
  TAccountNftMint,
  TAccountBidState,
  TAccountBidder,
  TAccountSystemProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? TENSOR_BID_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    nftMint: { value: input.nftMint ?? null, isWritable: false },
    bidState: { value: input.bidState ?? null, isWritable: true },
    bidder: { value: input.bidder ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  const instruction = {
    accounts: [
      getAccountMeta(accounts.nftMint),
      getAccountMeta(accounts.bidState),
      getAccountMeta(accounts.bidder),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getCancelBidInstructionDataEncoder().encode({}),
  } as CancelBidInstruction<
    TProgramAddress,
    TAccountNftMint,
    TAccountBidState,
    TAccountBidder,
    TAccountSystemProgram,
    TAccountRent
  >;

  return instruction;
}

export type ParsedCancelBidInstruction<
  TProgram extends string = typeof TENSOR_BID_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    nftMint: TAccountMetas[0];
    bidState: TAccountMetas[1];
    bidder: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
    rent: TAccountMetas[4];
  };
  data: CancelBidInstructionData;
};

export function parseCancelBidInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedCancelBidInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      nftMint: getNextAccount(),
      bidState: getNextAccount(),
      bidder: getNextAccount(),
      systemProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getCancelBidInstructionDataDecoder().decode(instruction.data),
  };
}
