/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type Frozen = { amount: bigint; time: bigint };

export type FrozenArgs = { amount: number | bigint; time: number | bigint };

export function getFrozenEncoder(): Encoder<FrozenArgs> {
  return getStructEncoder([
    ["amount", getU64Encoder()],
    ["time", getI64Encoder()],
  ]);
}

export function getFrozenDecoder(): Decoder<Frozen> {
  return getStructDecoder([
    ["amount", getU64Decoder()],
    ["time", getI64Decoder()],
  ]);
}

export function getFrozenCodec(): Codec<FrozenArgs, Frozen> {
  return combineCodec(getFrozenEncoder(), getFrozenDecoder());
}
