/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export enum PoolType {
  Token,
  NFT,
  Trade,
}

export type PoolTypeArgs = PoolType;

export function getPoolTypeEncoder(): Encoder<PoolTypeArgs> {
  return getEnumEncoder(PoolType);
}

export function getPoolTypeDecoder(): Decoder<PoolType> {
  return getEnumDecoder(PoolType);
}

export function getPoolTypeCodec(): Codec<PoolTypeArgs, PoolType> {
  return combineCodec(getPoolTypeEncoder(), getPoolTypeDecoder());
}
