/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { TCOMP_PROGRAM_ADDRESS } from "../programs";

/** ArithmeticError: arithmetic error */
export const TCOMP_ERROR__ARITHMETIC_ERROR = 0x17d4; // 6100
/** ExpiryTooLarge: expiry too large */
export const TCOMP_ERROR__EXPIRY_TOO_LARGE = 0x17d5; // 6101
/** BadOwner: bad owner */
export const TCOMP_ERROR__BAD_OWNER = 0x17d6; // 6102
/** BadListState: bad list state */
export const TCOMP_ERROR__BAD_LIST_STATE = 0x17d7; // 6103
/** BadRoyaltiesPct: royalties pct must be between 0 and 100 */
export const TCOMP_ERROR__BAD_ROYALTIES_PCT = 0x17d8; // 6104
/** PriceMismatch: price mismatch */
export const TCOMP_ERROR__PRICE_MISMATCH = 0x17d9; // 6105
/** CreatorMismatch: creator mismatch */
export const TCOMP_ERROR__CREATOR_MISMATCH = 0x17da; // 6106
/** InsufficientBalance: insufficient balance */
export const TCOMP_ERROR__INSUFFICIENT_BALANCE = 0x17db; // 6107
/** BidExpired: bid has expired */
export const TCOMP_ERROR__BID_EXPIRED = 0x17dc; // 6108
/** TakerNotAllowed: taker not allowed */
export const TCOMP_ERROR__TAKER_NOT_ALLOWED = 0x17dd; // 6109
/** BadBidField: cannot pass bid field */
export const TCOMP_ERROR__BAD_BID_FIELD = 0x17de; // 6110
/** BidNotYetExpired: bid not yet expired */
export const TCOMP_ERROR__BID_NOT_YET_EXPIRED = 0x17df; // 6111
/** BadMargin: bad margin */
export const TCOMP_ERROR__BAD_MARGIN = 0x17e0; // 6112
/** WrongIxForBidTarget: wrong ix for bid target called */
export const TCOMP_ERROR__WRONG_IX_FOR_BID_TARGET = 0x17e1; // 6113
/** WrongTargetId: wrong target id */
export const TCOMP_ERROR__WRONG_TARGET_ID = 0x17e2; // 6114
/** MissingFvc: creator array missing first verified creator */
export const TCOMP_ERROR__MISSING_FVC = 0x17e3; // 6115
/** MissingCollection: metadata missing collection */
export const TCOMP_ERROR__MISSING_COLLECTION = 0x17e4; // 6116
/** CannotModifyTarget: cannot modify bid target, create a new bid */
export const TCOMP_ERROR__CANNOT_MODIFY_TARGET = 0x17e5; // 6117
/** TargetIdMustEqualBidId: target id and bid id must be the same for single bids */
export const TCOMP_ERROR__TARGET_ID_MUST_EQUAL_BID_ID = 0x17e6; // 6118
/** CurrencyNotYetEnabled: currency not yet enabled */
export const TCOMP_ERROR__CURRENCY_NOT_YET_ENABLED = 0x17e7; // 6119
/** MakerBrokerNotYetEnabled: maker broker not yet enabled */
export const TCOMP_ERROR__MAKER_BROKER_NOT_YET_ENABLED = 0x17e8; // 6120
/** OptionalRoyaltiesNotYetEnabled: optional royalties not yet enabled */
export const TCOMP_ERROR__OPTIONAL_ROYALTIES_NOT_YET_ENABLED = 0x17e9; // 6121
/** WrongStateVersion: wrong state version */
export const TCOMP_ERROR__WRONG_STATE_VERSION = 0x17ea; // 6122
/** WrongBidFieldId: wrong field id */
export const TCOMP_ERROR__WRONG_BID_FIELD_ID = 0x17eb; // 6123
/** BrokerMismatch: broker mismatch */
export const TCOMP_ERROR__BROKER_MISMATCH = 0x17ec; // 6124
/** AssetIdMismatch: asset id mismatch */
export const TCOMP_ERROR__ASSET_ID_MISMATCH = 0x17ed; // 6125
/** ListingExpired: listing has expired */
export const TCOMP_ERROR__LISTING_EXPIRED = 0x17ee; // 6126
/** ListingNotYetExpired: listing not yet expired */
export const TCOMP_ERROR__LISTING_NOT_YET_EXPIRED = 0x17ef; // 6127
/** BadQuantity: bad quantity passed in */
export const TCOMP_ERROR__BAD_QUANTITY = 0x17f0; // 6128
/** BidFullyFilled: bid fully filled */
export const TCOMP_ERROR__BID_FULLY_FILLED = 0x17f1; // 6129
/** BadWhitelist: bad whitelist */
export const TCOMP_ERROR__BAD_WHITELIST = 0x17f2; // 6130
/** ForbiddenCollection: forbidden collection */
export const TCOMP_ERROR__FORBIDDEN_COLLECTION = 0x17f3; // 6131
/** BadCosigner: bad cosigner */
export const TCOMP_ERROR__BAD_COSIGNER = 0x17f4; // 6132
/** BadMintProof: bad mint proof */
export const TCOMP_ERROR__BAD_MINT_PROOF = 0x17f5; // 6133
/** CurrencyMismatch: Currency mismatch */
export const TCOMP_ERROR__CURRENCY_MISMATCH = 0x17f6; // 6134
/** BidBalanceNotEmptied: The bid balance was not emptied */
export const TCOMP_ERROR__BID_BALANCE_NOT_EMPTIED = 0x17f7; // 6135
/** BadRentDest: Bad rent dest. */
export const TCOMP_ERROR__BAD_RENT_DEST = 0x17f8; // 6136
/** CurrencyNotYetWhitelisted: currency not yet whitelisted */
export const TCOMP_ERROR__CURRENCY_NOT_YET_WHITELISTED = 0x17f9; // 6137
/** MakerBrokerNotYetWhitelisted: maker broker not yet whitelisted */
export const TCOMP_ERROR__MAKER_BROKER_NOT_YET_WHITELISTED = 0x17fa; // 6138
/** WrongTokenRecordDerivation: token record derivation is wrong */
export const TCOMP_ERROR__WRONG_TOKEN_RECORD_DERIVATION = 0x17fb; // 6139

export type TcompError =
  | typeof TCOMP_ERROR__ARITHMETIC_ERROR
  | typeof TCOMP_ERROR__ASSET_ID_MISMATCH
  | typeof TCOMP_ERROR__BAD_BID_FIELD
  | typeof TCOMP_ERROR__BAD_COSIGNER
  | typeof TCOMP_ERROR__BAD_LIST_STATE
  | typeof TCOMP_ERROR__BAD_MARGIN
  | typeof TCOMP_ERROR__BAD_MINT_PROOF
  | typeof TCOMP_ERROR__BAD_OWNER
  | typeof TCOMP_ERROR__BAD_QUANTITY
  | typeof TCOMP_ERROR__BAD_RENT_DEST
  | typeof TCOMP_ERROR__BAD_ROYALTIES_PCT
  | typeof TCOMP_ERROR__BAD_WHITELIST
  | typeof TCOMP_ERROR__BID_BALANCE_NOT_EMPTIED
  | typeof TCOMP_ERROR__BID_EXPIRED
  | typeof TCOMP_ERROR__BID_FULLY_FILLED
  | typeof TCOMP_ERROR__BID_NOT_YET_EXPIRED
  | typeof TCOMP_ERROR__BROKER_MISMATCH
  | typeof TCOMP_ERROR__CANNOT_MODIFY_TARGET
  | typeof TCOMP_ERROR__CREATOR_MISMATCH
  | typeof TCOMP_ERROR__CURRENCY_MISMATCH
  | typeof TCOMP_ERROR__CURRENCY_NOT_YET_ENABLED
  | typeof TCOMP_ERROR__CURRENCY_NOT_YET_WHITELISTED
  | typeof TCOMP_ERROR__EXPIRY_TOO_LARGE
  | typeof TCOMP_ERROR__FORBIDDEN_COLLECTION
  | typeof TCOMP_ERROR__INSUFFICIENT_BALANCE
  | typeof TCOMP_ERROR__LISTING_EXPIRED
  | typeof TCOMP_ERROR__LISTING_NOT_YET_EXPIRED
  | typeof TCOMP_ERROR__MAKER_BROKER_NOT_YET_ENABLED
  | typeof TCOMP_ERROR__MAKER_BROKER_NOT_YET_WHITELISTED
  | typeof TCOMP_ERROR__MISSING_COLLECTION
  | typeof TCOMP_ERROR__MISSING_FVC
  | typeof TCOMP_ERROR__OPTIONAL_ROYALTIES_NOT_YET_ENABLED
  | typeof TCOMP_ERROR__PRICE_MISMATCH
  | typeof TCOMP_ERROR__TAKER_NOT_ALLOWED
  | typeof TCOMP_ERROR__TARGET_ID_MUST_EQUAL_BID_ID
  | typeof TCOMP_ERROR__WRONG_BID_FIELD_ID
  | typeof TCOMP_ERROR__WRONG_IX_FOR_BID_TARGET
  | typeof TCOMP_ERROR__WRONG_STATE_VERSION
  | typeof TCOMP_ERROR__WRONG_TARGET_ID
  | typeof TCOMP_ERROR__WRONG_TOKEN_RECORD_DERIVATION;

let tcompErrorMessages: Record<TcompError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  tcompErrorMessages = {
    [TCOMP_ERROR__ARITHMETIC_ERROR]: `arithmetic error`,
    [TCOMP_ERROR__ASSET_ID_MISMATCH]: `asset id mismatch`,
    [TCOMP_ERROR__BAD_BID_FIELD]: `cannot pass bid field`,
    [TCOMP_ERROR__BAD_COSIGNER]: `bad cosigner`,
    [TCOMP_ERROR__BAD_LIST_STATE]: `bad list state`,
    [TCOMP_ERROR__BAD_MARGIN]: `bad margin`,
    [TCOMP_ERROR__BAD_MINT_PROOF]: `bad mint proof`,
    [TCOMP_ERROR__BAD_OWNER]: `bad owner`,
    [TCOMP_ERROR__BAD_QUANTITY]: `bad quantity passed in`,
    [TCOMP_ERROR__BAD_RENT_DEST]: `Bad rent dest.`,
    [TCOMP_ERROR__BAD_ROYALTIES_PCT]: `royalties pct must be between 0 and 100`,
    [TCOMP_ERROR__BAD_WHITELIST]: `bad whitelist`,
    [TCOMP_ERROR__BID_BALANCE_NOT_EMPTIED]: `The bid balance was not emptied`,
    [TCOMP_ERROR__BID_EXPIRED]: `bid has expired`,
    [TCOMP_ERROR__BID_FULLY_FILLED]: `bid fully filled`,
    [TCOMP_ERROR__BID_NOT_YET_EXPIRED]: `bid not yet expired`,
    [TCOMP_ERROR__BROKER_MISMATCH]: `broker mismatch`,
    [TCOMP_ERROR__CANNOT_MODIFY_TARGET]: `cannot modify bid target, create a new bid`,
    [TCOMP_ERROR__CREATOR_MISMATCH]: `creator mismatch`,
    [TCOMP_ERROR__CURRENCY_MISMATCH]: `Currency mismatch`,
    [TCOMP_ERROR__CURRENCY_NOT_YET_ENABLED]: `currency not yet enabled`,
    [TCOMP_ERROR__CURRENCY_NOT_YET_WHITELISTED]: `currency not yet whitelisted`,
    [TCOMP_ERROR__EXPIRY_TOO_LARGE]: `expiry too large`,
    [TCOMP_ERROR__FORBIDDEN_COLLECTION]: `forbidden collection`,
    [TCOMP_ERROR__INSUFFICIENT_BALANCE]: `insufficient balance`,
    [TCOMP_ERROR__LISTING_EXPIRED]: `listing has expired`,
    [TCOMP_ERROR__LISTING_NOT_YET_EXPIRED]: `listing not yet expired`,
    [TCOMP_ERROR__MAKER_BROKER_NOT_YET_ENABLED]: `maker broker not yet enabled`,
    [TCOMP_ERROR__MAKER_BROKER_NOT_YET_WHITELISTED]: `maker broker not yet whitelisted`,
    [TCOMP_ERROR__MISSING_COLLECTION]: `metadata missing collection`,
    [TCOMP_ERROR__MISSING_FVC]: `creator array missing first verified creator`,
    [TCOMP_ERROR__OPTIONAL_ROYALTIES_NOT_YET_ENABLED]: `optional royalties not yet enabled`,
    [TCOMP_ERROR__PRICE_MISMATCH]: `price mismatch`,
    [TCOMP_ERROR__TAKER_NOT_ALLOWED]: `taker not allowed`,
    [TCOMP_ERROR__TARGET_ID_MUST_EQUAL_BID_ID]: `target id and bid id must be the same for single bids`,
    [TCOMP_ERROR__WRONG_BID_FIELD_ID]: `wrong field id`,
    [TCOMP_ERROR__WRONG_IX_FOR_BID_TARGET]: `wrong ix for bid target called`,
    [TCOMP_ERROR__WRONG_STATE_VERSION]: `wrong state version`,
    [TCOMP_ERROR__WRONG_TARGET_ID]: `wrong target id`,
    [TCOMP_ERROR__WRONG_TOKEN_RECORD_DERIVATION]: `token record derivation is wrong`,
  };
}

export function getTcompErrorMessage(code: TcompError): string {
  if (process.env.NODE_ENV !== "production") {
    return (tcompErrorMessages as Record<TcompError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isTcompError<TProgramErrorCode extends TcompError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    TCOMP_PROGRAM_ADDRESS,
    code,
  );
}
